export const LOGIN_FORM_ERROR = 'LOGIN_FROM_ERROR';
export const LOGIN_FORM_INPUT_CHANGE = 'LOGIN_FORM_INPUT_CHANGE';
export const LOGIN_FORM_SUCCESS = 'LOGIN_FORM_SUCCESS';
export const LOGIN_FORM_LOADING = 'LOGIN_FORM_LOADING';

export const AUTH_USER = 'AUTH_USER';
export const LOG_OUT = 'LOG_OUT';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const DELETE_USER = 'DELETE_USER';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';